# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET - Playwright MSTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: dotnet build ./MSTestPlaywright/MSTestPlaywright.sln
    - name: Install Playwright browsers
      run: pwsh ./MSTestPlaywright/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run tests
      run: dotnet test ./MSTestPlaywright/MSTestPlaywright.sln --verbosity normal
