# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET - MSTest tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MSTestPlaywright/MSTestPlaywright.sln
    - name: Install Playwright browsers
      # run: pwsh bin/Debug/net8.0/playwright.ps1 install
      run: ls -lah
    - name: Run tests
      run: dotnet test ./MSTestPlaywright/MSTestPlaywright.sln --no-restore --verbosity normal
